# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46423166f8bc32b0d1250353b326c29dc5feca290fd2f53544a25541f343987e79daeec25ea1d0384d78abcb66914511be17bd0ac690bcee94e4ba8a17cce4ac

test:
  secret_key_base: 5099dd7969a28bb1568fa70b8c4f1ffc0c61bd1bbfd94fc29462c9d2c9f5d0d5466c4c4cdcd68a08f14824f33b10a39b7804aadaae664ce0a78baac9c5760ce8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
