# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13956bcceb6c0371d28404d69f0ccf7f633ef57f71a7ebde634dfd3a793e9ae8239d8ea32a82268c66653eb1a119afe29c5dec5b77bbe50a73754a7160882497

test:
  secret_key_base: c18656fd67ee6a616e3af86220d7344e767343e7d43ff90ac2b4315a5cd575e3fb47bf7c2ac76bdba8b47cdb4ee0efe78d18c0b9bb32ad54fca3f3706b14cd83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
